name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: 6.1.1
  firebase_core: 4.2.0 
  cloud_firestore: 6.0.3
  
  freezed_annotation: 3.1.0
  mask_text_input_formatter: 2.9.0
  common_base: 
    path: ../common_base
  network: 
    path: ../common_base/modules/network 
  
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: 3.1.0
  json_serializable: 6.9.5
  build_runner: 2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
               

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

