name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dropdown_button2: 2.3.9
  objectbox_flutter_libs: 4.3.0
  objectbox: 4.3.0
  freezed_annotation: 3.1.0
  firebase_auth: 6.1.1
  firebase_core: 4.2.0
  cloud_firestore: 6.0.3
  analyzer: 7.7.1

  common_base: 
    path: ../common_base
  network: 
    path: ../common_base/modules/network
  flutter:
    sdk: flutter

dev_dependencies:
  objectbox_generator: 4.3.0
  freezed: 3.1.0
  build_runner: 2.5.4
  json_serializable: 6.9.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides: 
  source_gen: ^2.0.0



flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

