name: common_base
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  talker: 5.0.2
  mask_text_input_formatter: 2.9.0
  firebase_auth: 6.1.1
  firebase_core: 4.2.0 
  cloud_firestore: 6.0.3
  flutter_svg: 2.2.1
  intl: 0.19.0
  get_it: 8.2.0
  bloc: 9.1.0
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  network:
    path: modules/network 
  navigation: 
    path: modules/navigation 
  home:  
    path: ../home
  auth: 
    path: ../auth

  

dev_dependencies:
  build_runner: 2.5.4
  flutter_gen_runner: 5.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_gen:
  fonts:
    outputs:
      package_parameter_enabled: true
  assets:
    outputs:
      package_parameter_enabled: true
      directory_path_enabled: true
  output: lib/gen/
  line_length: 80
  integrations:
    image: true
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

